version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 1ms 
      MYSQL_ROOT_PASSWORD: bN7kB7s5aPKJ6i
      MYSQL_DATABASE: iot_metrics_db
      MYSQL_USER: iot_metrics_user
      MYSQL_PASSWORD: BgdXHgrf8ZDEUP
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - IoT_Metrics_Network
    
volumes:
  mariadb_data:

networks:
  IoT_Metrics_Network:
    external: true