version: "3.2"
services:
  iot-metrics-hub:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    entrypoint: ["sh", "./docker/python/entrypoint.sh"]
    privileged: true
    env_file: ./env/development.env
    environment: 
      LOCALHOST: ${LOCALHOST}
    ports:
      - 5000:5000
    networks:
      - IoT_Metrics_Network
    volumes:
      - ./:/app
networks:
  IoT_Metrics_Network:
    external: true
