version: '3'
services:
  chronograf:
    image: chronograf:latest
    ports:
      - 8888:8888
    volumes:
      - chronograf_data:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=iot_metrics_user
      - INFLUXDB_PASSWORD=BgdXHgrf8ZDEUP
      - INFLUXDB_DATABASE=iot_metrics_db
    networks:
      - IoT_Metrics_Network

volumes:
  chronograf_data:

networks:
  IoT_Metrics_Network:
    external: true