
version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    volumes:
      - influxdb_data:/var/lib/grafana
    networks:
      - IoT_Metrics_Network
      
volumes:
  influxdb_data:

networks:
  IoT_Metrics_Network:
    external: true
