version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - IoT_Metrics_Network
  
networks:
  IoT_Metrics_Network:
    external: true

volumes:
  redis_data:
