"""device

Revision ID: e0222733cc05
Revises: 09e70c11e3bc
Create Date: 2024-02-29 03:04:20.978625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0222733cc05'
down_revision = '09e70c11e3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
