version: '3'

services:
  kong:
    image: kong:latest
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=localhost
      - KONG_PG_USER=iot_metrics_user
      - KONG_PG_PASSWORD=BgdXHgrf8ZDEUP
      - KONG_PG_DATABASE=iot_metrics_db
    depends_on:
      - kong-database
    networks:
      - IoT_Metrics_Network

networks:
  IoT_Metrics_Network:
    external: true