version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: iot_metrics_user
      POSTGRES_PASSWORD: BgdXHgrf8ZDEUP
      POSTGRES_DB: iot_metrics_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - IoT_Metrics_Network
    
volumes:
  postgres_data:

networks:
  IoT_Metrics_Network:
    external: true